### PR TITLE
GUI: fix log (use document length instead of offset)

### PR DESCRIPTION
**Pull request by arisona**
Background: Previously threw with JDK10, now works as expected.

### CODE REVIEW

**Comment by arisona** [comment]
Any insights why CI fails? First build failed, but second went through...

**Comment by nicolasmiller** [comment]
Not clear what happened with the Linux build. It just timed out I think. I don't have write access to the main repo so I can't manually restart. The build will restart if you close and open the pull request though.

What is the exception that is thrown here in JDK10? Looking at the docs for 10, the original methods are still there. It seems like getLength() should be equivalent exactly like you have here though. I think the distinction is that if you hold a reference to the Position object that getEndPosition() returns, it will track the end position over time as edits are made and . But we were just discarding that reference immediately, getting the length should be the same thing.

I'm a little bit surprised that this is the only spot that fails under JDK10. As far as I know, there hasn't been a significant effort to target versions more recent than 8; that's sort of the current canonical API level for the project. But the build process ultimately uses whichever system java it finds; it doesn't enforce using a particular API level. I don't think that there are significant technical reasons why we can't target more recent versions. It's just going to take a bit of testing to find issues. We should be better about documenting exactly which versions are supported and how to build for them.

**Comment by nicolasmiller** [comment]
Wow, the 1, 0 behavior is pretty confusing. I was worried there would be some kind of off by one thing happening there. I'm going to do a little bit more digging to figure out why that might be happening.

**Comment by nicolasmiller** [comment]
What I've found so far: getEndPosition().getOffset() seems to always be length + 1. In Java 8 inserting beyond the end just inserts at the end. So when we try to to insert at index 1 but the doc length is 0 it doesn't throw an exception. Java 9 and higher will throw.

**Comment by JohannesTaelman** [comment]
Thanks!
I'm hesitant to upgrade to JDK 9 or 10 as they will have a very short lifetimes, and seem to drop support for older systems (32bit...). Yet it is good to prepare for the future...

**Pull request merged**
